name: Clearmatics libsnark library

on:
  push:
  pull_request:

jobs:
  build-ubuntu:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        compiler: [g++]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: format-check
      run: |
        scripts/format
        git diff --no-ext-diff > format_errs
        head -n 20 format_errs
        [ `cat format_errs | wc -l` == "0" ]
    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential git libboost-all-dev cmake libgmp3-dev libssl-dev libprocps-dev pkg-config
    - name: configure
      env:
        CXX: ${{ matrix.compiler }}
        CXXFLAGS: "-Werror"
      run: mkdir build && cd build && cmake -DDEBUG=1 -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
    - name: build
      run: cd build && make -j $(($(nproc)+1))
    - name: test
      run: cd build && CTEST_OUTPUT_ON_FAILURE=1 make check -j $(($(nproc)+1))
