name: Clearmatics libsnark library

on:
  push:
  pull_request:

jobs:
  build-ubuntu:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v2
    - name: install-dependencies
      run: sudo apt-get install build-essential git libboost-all-dev cmake libgmp3-dev libssl-dev libprocps-dev pkg-config
    - name: init-submodules
      run: git submodule init && git submodule update
    - name: configure
      env:
        CXX: ${{ matrix.compiler }}
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cd build && make
    - name: test
      run: cd build && make check
